### ISSUE TITLE
Projucer 5 (win) doesn't add new files in the vsproject

### ISSUE THREAD

**Issue by benkuper** [WeAreROLI/JUCE#193] opened 2017-04-30 13:13 UTC
When adding new files (or existing ones) in the projucer file manager, then saving the VS project and opening it in Visual Studio, the newly added files appear with a "+" icon and when using auto-completion or auto code-generation, VS says that the file is not included in the project.
When right-clicking the file in the file explorer in VS, it shows indeed a lot less option than other files.

**Comment by ed95** [comment] 2017-05-09 08:24
What version of VS is this? I can't reproduce it with VS2017

**Comment by benkuper** [comment] 2017-05-17 15:46
I've been misreading the "+" icon which is related to git (and VS automatically detecting it), but i've got crashes when saving from Projucer5 and trying to to Ctrl + ";" and generate automatically the functions from header function definitions.

**Comment by benkuper** [comment] 2017-05-17 17:31
In VS2015, the editor just crashed, in VS 2017 i got this error when saving from projucer to exporter VS2017 and then trying to use intellisense to generate a function in the .cpp from the .h :

> The operation 'Create declaration / Definition' could not be completed for the following reason:
> The attempt to modify the file "[...]\MyClass.cpp" failed because the file is not in the current project.
> 
> Please add it to the project and try again.
> 
> Function signature was copied to the clipboard.

**Comment by benkuper** [comment] 2017-05-17 17:39
Moreover, when i check in the Solution explorer, in JUCE5/VS2017, there is now a project called "MyProject_App", and i can clearly that some of my files are just not there, these are the files i can't use intellisense on, and those files are all the files i created from Projucer 5.0.1
All my past files are there, in the projucer explorer, everything is OK, the new files are here just like the others, i tried deleting the builds folder and resaving, nothing is working, and this quite a blocker..

**Comment by hogliux** [comment] 2017-05-18 12:52
This is now fixed on the develop branch with the following commit: [14d7675](https://github.com/WeAreROLI/JUCE/commit/14d7675c48b54c5ecf6d45f6fa77d73079ca635c)

**Closed by hogliux** 2017-05-18 12:52 UTC

**Comment by benkuper** [comment] 2017-05-18 13:09
I confirm, this is MUCH better, thanks and wow for the fast fix !
