### ISSUE TITLE
Plugin standalone version window doesn't change size

### ISSUE THREAD

**Issue by reFX-Mike** [WeAreROLI/JUCE#210] opened 2017-06-09 00:19 UTC
```
	setResizeLimits (150, 100, 600, 400);
	getConstrainer ()->setFixedAspectRatio (1.5);
	setSize (600, 400);
```

When you click on the resizer control in the bottom right corner, the editor resizes, but the standalone window retains it's full size.

Windows 10, 64-bit

**Comment by fab672000** [comment] 2017-06-09 00:55
It seems that this bug is happening easily when using the audio plugin standalone version and then hiding and showing again the piano keyboard using the bottom right resizer corner on mac os x.

**Comment by fab672000** [comment] 2017-06-09 01:17
In the audio plugin demo in osx, it does resize vertically but not horizontally and yet both width and height are resized in the editor if user attempts to resize width and/or height.

**Comment by tpoole** [comment] 2017-06-09 11:24
@reFX-Mike Is this with the JUCE Demo Plug-in? I can't reproduce the behaviour you've reported.

@fab672000 How are you hiding and showing the piano keyboard using the resizer corner?

For me it's working as expected on both Win 10 and OS X.

**Comment by fab672000** [comment] 2017-06-09 14:06
IMO, It is not working as it should be cause if you try hiding then showing again the keyboard, it also unfortunately resizes the width of the editor content object (i.e. the keyboard but also other elements displayed there) making them truncated because the parent main window of the standalone app does _not_ resizes horizontally (only vertically).
At the very least, if it is too hard to resize horizontally the main window so that the container content is entirely visible ; then it should not allow horizontal resizing.
If you try to grow the window size dragging diagonally you'll notice what I explained immediately, as I tested on OSX 10.12.5.

**Comment by tpoole** [comment] 2017-06-09 14:27
I think you misunderstood my question; I was trying to find out *how it is possible* to hide and show the keyboard by resizing. As far as I can see there's no way that this can happen. Could you provide a video or some screenshots to show us what's happening?

As I said before, I can't reproduce the problem: everything is resizing correctly when I drag diagonally.

Are you using the latest version of JUCE?

**Comment by fab672000** [comment] 2017-06-09 16:33
1. I used released version 5.0.2 of JUCE that I dowloaded yesterday from the JUCE website.
2. I used OSX 10.12.5 (sierra), and build the audio plugin VST/AU/Standalone demo demo with Xcode 8.3.2.
3. I built the demo in standalone and 64-bit mode
4. I cannot shoot a video ATM but it is very easy to reproduce on release 5.0.2 version of JUCE ; will try from Github tonight see if it's already there.
5. Just used the bottom right resize corner but take care of not drag only vertically but also horizontal and try to grow the window (even if the main window of course won't resize horizontally)

Hope that helps,
-Fab

**Comment by reFX-Mike** [comment] 2017-06-09 16:48
@tpoole No, it's not with the demo plugin. I haven't tried that. It seems the resized behavior stops at the main-component and doesn't propagate to the main window.

If I use the VST version, it works just fine. Only the stand-alone version doesn't resize it's top-level window. The main-component resizes just fine.

![resize-bug](https://user-images.githubusercontent.com/2496353/26985517-9ea5b532-4cf8-11e7-829f-624a088c36bb.jpg)

I've resized my plugin, and you can see the dark-gray area where the window stayed the same size.

**Comment by m-hilgendorf** [comment] 2017-06-09 17:49
Also experiencing this issue with 64-bit standalone plugins on OSX 10.11, but I'm not using the keyboard component. Seems to be tied to using the ResizeableCornerComponent to resize the plugin editor, which like @reFX-Mike said works fine, but the main window will lag behind the plugin editor component's resizing.

**Comment by reFX-Mike** [comment] 2017-06-09 18:14
Yeah, it has nothing to do with the keyboard component. That's just coincidence that I used it as well. No idea why @fab672000 tries to make that connection. Maybe he's talking about something else?

It's really just the top-level window that is not resizing.

**Comment by fab672000** [comment] 2017-06-09 19:23
@reFX-Mike  I don't try to make any confirmed connection until root cause is determined, 
@tpoole glad that you could finally reproduce it, remember: it is my first try of the toolkit so  I'm not pretending knowing the answer to life universe and the rest (wasn't it 42 though? :) ).

**Comment by fab672000** [comment] 2017-06-09 22:53
>It's really just the top-level window that is not resizing.
@reFX-Mike still not entirely correct as the top level window _does_ resize in some cases (see upperwhere obviously vertical resizing happens in my OSX example) but when it is constrained though,  like in the audio plugin example standalone case, it seems that its content is _not_ constrained and does resize.

**Comment by fab672000** [comment] 2017-06-09 23:31
> I was trying to find out how it is possible to hide and show the keyboard by resizing. As far as I can see there's no way that this can happen. Could you provide a video or some screenshots to show us what's happening?


@tpoole on OSX at least (did not test on Windows) you can hide the keyboard (or make it not visible anymore is more accurate)  as a result of the content objects (including the keyboard being resized vertically and bigenough to get clipped by the main window.

Here's a snapshot of what i can easily get on 5.0.2:

![keyboardnotvisible asaresultofresizingvertically](https://user-images.githubusercontent.com/6124901/26997723-9a4ed6dc-4d41-11e7-8e84-b8ad4a35318e.png)

**Comment by reFX-Mike** [comment] 2017-06-09 23:34
@fab672000 can you please open your own issue for this and stop hi-jacking this issue?

You harp on and on about a keyboard component vanishing etc. and it seems to have *nothing* to do with the issue I've reported.

You're confusing everyone, mostly yourself, and this is not helping.

**Comment by fab672000** [comment] 2017-06-09 23:37
@reFX @tpoole asked for evidence data, I could not do the video but could provide a snapshot. Are we sure it is not another instance of the issue before suggesting to open a new one ?

**Comment by reFX-Mike** [comment] 2017-06-09 23:40
I'm sure it's some kind of language barrier here. Why do you keep bringing up the keyboard?

Or are you saying that if you make the contents of the window so large that it's outside the top-level window, then it's (obviously) no longer visible?

**Comment by fab672000** [comment] 2017-06-09 23:41
You gotg it and yes this is not my native language, not a barrier though for those who can make the effort.

**Comment by reFX-Mike** [comment] 2017-06-09 23:42
Sigh, so it's my fault for not understanding you, not yours for expressing yourself poorly? Sure.

**Comment by fab672000** [comment] 2017-06-09 23:44
Please keep the discussion , problem solving related and avoid emotional/flaming content. I am sorry if you feel frustrated but there is nothing personal here. and my feedback is more for tpoole ATM, not for you so please let him answer and stop interrupting with non constructive noise.

**Comment by reFX-Mike** [comment] 2017-06-09 23:45
@fab672000 blocked.

**Comment by tpoole** [comment] 2017-06-12 08:24
I've tried to reproduce this a few times, but I can't. Here are some screenshots of a modified JUCE demo plug-in with the same resize constraints as in your first post.

<img width="604" alt="screen shot 2017-06-12 at 09 14 31" src="https://user-images.githubusercontent.com/872729/27024835-25ada68a-4f50-11e7-8a37-89a6fd1edbb1.png">
<img width="154" alt="screen shot 2017-06-12 at 09 14 45" src="https://user-images.githubusercontent.com/872729/27024836-25af0566-4f50-11e7-8463-6994548a4cbc.png">

Everything is working as expected; I can't see any lag or mis-sized areas. If you can demonstrate the problem in one of our demo plug-ins that would be much more helpful.

**Comment by reFX-Mike** [comment] 2017-06-12 18:42
If I take the unmodified JuceDemo Plugin (again, completely unmodified, exactly the source from the 5.0.2 release) I can already reproduce the bug. The demo plugin has a midi-keyboard, and if you attempt to resize the window, the keyboard moves with the new size (it's stuck to the bottom of the plugin window) but in the stand-alone version the actual top-level window itself doesn't resize, so the keyboard vanishes as it's now outside of the top-level window.

If I change the code in the constructor (essentially only adding the resizing restriction to a fixed aspect-ratio) I still get the exact same behavior, except now it's a fixed aspect ratio.

How about you do a remote-desktop session with me, so I can show you the problem first hand?

**Comment by m-hilgendorf** [comment] 2017-06-12 20:39
@tpoole you don't need to modify the demo plugin at all to show this problem. [Here's a gif](https://giphy.com/gifs/10B2S2hRFo5cEE/fullscreen). 

This is compiled with JUCE 5.0.2 on OSX 10.11.6, no settings changed at all.

**Comment by tpoole** [comment] 2017-06-13 08:18
Apologies - this is something we had already fixed on the develop branch. I've cherry picked the corresponding commits to master.

**Closed by tpoole** 2017-06-13 08:18 UTC
