### ISSUE TITLE
Bug in Component::toBehind

### ISSUE THREAD

**Issue by OlivierSohn** [WeAreROLI/JUCE#627] opened 2019-11-01 12:11 UTC
https://github.com/WeAreROLI/JUCE/blob/724ae27c71ef809b836df06713cf9e50bc14162b/modules/juce_gui_basics/components/juce_Component.cpp#L942

I think the line above should be replaced by a "return" statement because at this point, the components are already ordered in the right order.

**Comment by julianstorer** [comment] 2019-11-01 12:14
Maybe you misunderstood what the function is supposed to do? 

It doesn't just move the component to *anywhere* behind the other, it moves it to be immediately behind and next to the other one (which may involve moving it forwards)

**Closed by julianstorer** 2019-11-01 12:14 UTC

**Comment by OlivierSohn** [comment] 2019-11-01 12:18
That's not what it is doing

**Comment by OlivierSohn** [comment] 2019-11-01 12:23
You can easily see that there is a bug by unit testing it, with all possible positions

**Comment by OlivierSohn** [comment] 2019-11-01 12:24
And I think this method is of little use anyway because yes it reorder (when it works) the 2 components, but it changes the order that you set for other components, so I'll refrain using it and just rely on the addAndMakeVisible order

**Comment by julianstorer** [comment] 2019-11-01 12:30
I don't need to write a test to see that if you changed it to a 'return' like you suggest, then it would have no effect on components that are behind the target but not adjacent to it. So that'd change the behaviour of the function, and silently break a ton of user code that relies on it.

And no, it won't reorder any other components (?) It just moves one of them, and the others all maintain their relative order.

You seem to be making a lot of odd claims about this function, maybe you've just got the wrong end of the stick about what it's supposed to do and are misinterpreting its intended behaviour as being wrong.

**Comment by OlivierSohn** [comment] 2019-11-01 12:33
I agree that return was the wrong fix, but still I think there is a problem if index > otherIndex, because in that case it swaps the 2 elements but doesn't put one immediately behind the other. Or am I missing something?

**Comment by OlivierSohn** [comment] 2019-11-01 12:36
Let me open another issue to clarify

**Comment by OlivierSohn** [comment] 2019-11-01 12:43
#628
